### PR TITLE
Add app sub generator to blueprint generator

### LINKED ISSUE #58: Support app subgenerator
JHipster allow overriding the `app` subgenerator since version 6.6.0 : https://github.com/jhipster/generator-jhipster/pull/10752
https://github.com/jhipster/generator-jhipster/pull/10752

### PR DESCRIPTION
**Pull request by avdev4j**
fix #58

### CODE REVIEW

**Comment by avdev4j** [comment]
@pascalgrimaud any idea about CI failing ?

**Comment by pascalgrimaud** [comment]
@avdev4j : it looks like there is 2 problems:
- Travis are not correct any more, and instead of updating the build, we should remove it
- Azure: there is a real issue I think

**Comment by mshima** [comment]
Is there a reason to link git master instead of using latest?
Look is npm messing with linked folders to me.

**Comment by pascalgrimaud** [comment]
@mshima : the CI part needs to be reviewed, as it is not maintain since months. That's why I think there is an issue with different npm link

**Comment by pascalgrimaud** [comment]
@avdev4j : can you rebase against master plz ?

**Comment by avdev4j** [comment]
hi @pascalgrimaud 
I don't understand. My branch is already up to date with master.

**Comment by mshima** [comment]
Hi @avdev4j to run the updated ci with your changes.

**Comment by avdev4j** [comment]
my bad, I forget to fetch upstream :D

**Comment by avdev4j** [comment]
@mshima it seems the following line throw an error: ttps://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-blueprint.js#L98

`isPackageRegistered` is not a function.

Because you did the modification, I hope you can help me on this point and why during integration tests it's fail.

**Comment by mshima** [comment]
> Because you did the modification, I hope you can help me on this point and why during integration tests it's fail.

This is due the created blueprint depends on older versions of the modules.
Removed all unnecessary dependencies on https://github.com/jhipster/generator-jhipster-blueprint/pull/64.

**Comment by pascalgrimaud** [comment]
@avdev4j : you need to rebase again plz

**Comment by avdev4j** [comment]
done ;)

**Comment by yelhouti** [comment]
@avdev4j @mshima I upgraded my blueprint to use 6.8.0 and now I'm getting the same error:
> `isPackageRegistered` is not a function.

could you guys enlighten me on what to do to have this fixed, my test looks like this:
```
helpers
                .run('generator-jhipster/generators/app')
                 .inDir(testDir, dir => {
                    // importJdl doesn't haev a call back there we call the generators manually after it updates the json files
                    testDir = dir;
                    fse.copySync(path.join(__dirname, '../test/templates/primeng-blueprint-test'), dir);
                    importJdl(['jhipster.jh'], { skipInstall: true, noInsight: true, interactive: false, 'skip-git': false }, {}, noopFork);
                })

```
thanks in advance

**Comment by mshima** [comment]
Try removing yeoman-test and reinstalling.

**Comment by yelhouti** [comment]
@mshima it seems you are right, yeoman-test dependency needs to be updated

**Comment by mshima** [comment]
@yelhouti the problem is that jhipster requires yeoman-environment 2.8.1 and yeoman-test is creating an instance of yeoman-environment < 2.8.1.
You can try the following:
- Remove yeoman-environment from dev dependency.
- Reinstall yeoman-test
- Last fix it to recreate package-lock.json

**Comment by yelhouti** [comment]
@mshima sorry if I wasn't clear in my previous message, updating yeoman-test in dev dependencies works !

**Comment by mshima** [comment]
@yelhouti 👍 
I am documenting the problem too.

**Pull request merged**
