### PR TITLE
Update logo and links

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by murdos** [comment]
@pascalgrimaud this PR contains a commit (eb9f959) that is unrelated to logo an links

**Comment by pascalgrimaud** [comment]
yes I know, sorry.
I saw build failed, so I fixed the migration from travis folder to test-integration
Then, I saw node is not up to date, so I did it in the same PR

**Comment by pascalgrimaud** [comment]
I could split tomorrow if you prefer, for having clean git log.

**Comment by murdos** [comment]
No, clean git log is not a problem... but I don't understand: these changes have already made in https://github.com/jhipster/generator-jhipster-blueprint/pull/14/files and master already contains nodejs 10.13 and npm instead of yarn: https://github.com/jhipster/generator-jhipster-blueprint/blob/master/.travis.yml

**Comment by murdos** [comment]
Take a well deserved rest ;-)

**Comment by pascalgrimaud** [comment]
PR updated
Thanks @murdos

**Pull request merged**
