### PR TITLE
Generate sample unit tests

### LINKED ISSUE #7: Generate sample unit tests
Generate sample unit tests like https://github.com/jhipster/generator-jhipster/pull/8365/files

### PR DESCRIPTION
**Pull request by murdos**
Excepted for entity-* subgenerators since they can't be easily tested with unit tests.
Fixes #7

### CODE REVIEW

**Comment by murdos** [comment]
@deepu105 done. Let's wait for the CI now ;-)

**Comment by deepu105** [comment]
@murdos CI seems to be failing

**Comment by murdos** [comment]
@deepu105 There are errors during unit tests that require deeper investigations.

What doesn't help is that since a week or two, mocha tests are stuck on my laptop: the first test starts and never ends. Have you already have that?

**Comment by deepu105** [comment]
No, I didn't

Thanks & Regards,
Deepu

**Comment by murdos** [comment]
FYI I'll open an issue - at least for documenting it - in generator-jhipster to describe an edge case in loading blueprint when mixed with npm linked modules, that is the root of the issue here.
I already encountered this issue locally a few weeks ago, but wasn't sure it was worth the effort.

**Comment by murdos** [comment]
@pascalgrimaud is there a possibility of something broken, a cache that doesn't update or something like that with Travis? 
Because I tried to reproduce errors raised by Travis, both on my usual workstation with Windows, and even on Linux, and everything works fine locally :(

**Comment by pascalgrimaud** [comment]
@murdos : ok, I'll have a look tomorrow

**Comment by pascalgrimaud** [comment]
@murdos : I fixed the issue but I did a rebase in my branch, so I couldn't PR against yours.
You can see the code: https://github.com/pascalgrimaud/generator-jhipster-blueprint/commits/murdos-generate-unit-tests
If you can take the code, the problem was just related to npm link order

Or, I'll be able to do a clean branch tonight

**Comment by murdos** [comment]
@pascalgrimaud Thanks!! I should be able to integrate the fix this evening.

**Comment by deepu105** [comment]
Made a release

**Comment by murdos** [comment]
@deepu105 have you merged the other pending PR for the release?

**Comment by deepu105** [comment]
Just did, and did another release

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Btw I added you guys to blueprint repo with write permissions

Thanks & Regards,
Deepu

**Pull request merged**
