### PR TITLE
Custom subgenerator generation

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
As https://github.com/jhipster/generator-jhipster/pull/9574 was merged, we can now provide it using blueprint generator.

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
Hi @murdos, thanks for the review.
The main reason of this feature is this need: https://github.com/jhipster/jhipster-vuejs/issues/327.
We will implement this using a custom subgenerator.

I agree on asking for the subgen name, I'll update this and check for the CI failure.

**Comment by pascalgrimaud** [comment]
Sorry about CI failure, I don't know what happened here.
The CI is broken since weeks and I didn't have a look yet

**Comment by murdos** [comment]
>
> The main reason of this feature is this need: [jhipster/jhipster-vuejs#327](https://github.com/jhipster/jhipster-vuejs/issues/327).
> We will implement this using a custom subgenerator.

Thanks, I understand now :)
 
> I agree on asking for the subgen name, I'll update this and check for the CI failure.

Well, let's wait for other input (@pascalgrimaud , @deepu105) before working again on it, since as I said, I'm not sure we should add this feature to `generator-jhipster-blueprint`

**Comment by murdos** [comment]
Closing this proposal, since it seems to be a very advanced feature that is not needed by most blueprints.

**Pull request closed without merging**
